esphome:
  name: pico-plant1
  friendly_name: Pico_Plant1

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "****REDACTED****"

ota:
  password: "****REDACTED****"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Pico-Plant1 Fallback Hotspot"
    password: "****REDACTED****"

#LED Blinker
switch:
  - platform: gpio
    pin:
      number: 32
      mode: output
    id: LED
interval:
  - interval: 10s
    then:
      - switch.turn_on: LED
      - delay: 500ms
      - switch.turn_off: LED


# Moisture Sensor    
sensor:
  - platform: adc
    pin: GPIO26
    name: "Soil Moisture"
    update_interval: 10s
    unit_of_measurement: "%"
    filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear:
        - 2.7 -> 100.00
        - 2.18 -> 0.00
    - lambda: |-
        if (x < 1) {
          return 0;
        } else {
          return (x);
        }
    accuracy_decimals: 0
    
# Analog Output Voltage Value
  - platform: adc
    pin: GPIO26
    name: "Soil Moisture Voltage"
    update_interval: 10s
    unit_of_measurement: "V"
    # Take 4 measurements and return the median 
    filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 1
    accuracy_decimals: 2
    
# Input Voltage Value
#   - platform: adc
#     pin: VSYS
#     name: "Pico Input Voltage"
#     update_interval: 60s
#     unit_of_measurement: "V"
#     accuracy_decimals: 2
